In [ ]:
# numpy
# int float str Bool    list, tuple ,set ,dictionary
# 파이썬에서 배열의 장점때문에 배열을 사용하고 싶은데, 기본적으로 없음
# numpy 라이브러리     내부적으로는 C처럼 구현되어있다.(=빠르다)

# 학습목표
# 1. 배열과 리스트 차이
# 2. numpy 기본 사용법 ( 조금 많음. )
# 3. numpy를 사용해서 원하는 배열을 만들 수 있다.
# 4. 랜덤배열만들기 + 통계내기

# 중요한거 몇개는 외우는데(많이 보다보면 외워질겁니다.),  내용이 이해는 가야됩니다.

# np.array 인덱싱, 슬라이싱 + 배열인덱싱
# np.ones, np.zeros
# np.reshape, flatten
# stack
# 배열연산 +(말고 여러가지)     행개수 or 열개수가 같으면 자동으로 데이터 생성해서 연산
# 통계 (var,min,max,mean,argmin,argmax,sort, median, std ...)

# 랜덤  # random 발생 randint, count_zeros, unique, bincount 등

In [ ]:
# 배열 선언 
import numpy as np
list = [0,1,2,3,4,5]
arr = np.array(list)
print(arr)
print("list타입" , type(list))
print("arr타입" , type(arr) )



In [ ]:
list = [0,1,2,3,4,5,6,7,8,9]
arr = np.array(list)

print( arr * 2)
print()
a = np.array([0,1,2])
b = np.array([10,20,30])
print(a+b)       # 기본적으로는 배열의 크기가 같으면 산술연산 가능
print(a*b)
print(a==2)
print(b>10)
print(( a==2 ) | (b>10) )     # 파이썬에서 논리연산은 and/or 이지만 numpy에서 논리연산은 &/| 을 사용해야한다.

In [ ]:
a= np.array([ [0,1,2],[3,4,5]   ])  #이차원 배열 행렬     [2] x [3] 행렬
print( len(a) ) # 2
print (len(a[0])) # 3

a=np.array( [ [ [0,1], [2,3], [3,4] ], [ [5,6],[7,8],[9,10] ] ])    # 삼차원 배열 [2][3][2] 행렬
print(len(a))
print(len(a[0]))
print(len(a[0][0]))

In [ ]:
# 인덱싱, 슬라이싱        
# [인덱스 , 길이]
a=np.array( [0,1,2,3,4] )
print(a[  :  ])  # 전체
print(a[1 : 2])  # 추측 : 1
print(a[ : 5])   # 추측 : 0 1 2 3 4 
print(a[ 3: ])   # 추측 : 3 4
print(a[ 2:-2 ]) # 추측 : 2


print("--------------")
b=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])    # [3][4] 이차원배열
print(b[0, :] )  # [0 1 2 3]

#[0] [4] [8]
print(b[0][0:1], b[1][:1], b[2][:1])

#[2,3] [6,7] [10,11]
print(b[0][2:4], b[1][2:4],b[2][2:4])
# [4,5] [8,9]
print(b[1][0:2], b[2][0:2])

# [0] [-1] ==> 결과는? // 3
print(b[0][-1])

# 7을 얻고 싶으면 
print(b[1][3])

print(b [ : , : 2])

print(b [ : , :: 2  ])  # 시작:끝 step -> 짝수만 출력

In [ ]:
# 배열 인덱싱 : 배열을 배열로 인덱싱
a=np.array([0,1,3,6,9,12,15,18,21,24])
idx = np.array( [0,2,4,6,8] )
print(a[idx] )

a=np.array( [ [0,1,2,3], [4,5,6,7], [8,9,10,11] ])  # [3][4]
idx = np.array ( [ 0,0,0,1,1,2 ])
print(a[idx, 1:3])  # [1 2] [1 2] [1 2] [5 6] [5 6] [9 10]

a=np.array( [0,1,2,3,4,5,6,7,8,9,10] )
print(a%2 ==0) # [ True False  True False  True False..]
print (a[a%2==0] )  # 2의 배수 0제외
print(a[a%3==0])    # 3의 배수 0제외

print(a[(a%2==0) & (a%3==0) & (a!=0)])  # 6의 배수

In [ ]:
# 배열의 타입
# 배열 안의 타입 알아서 잘 판단합니다.
a = np.array( [1,2,3], dtype='i' ) # dtype='i' -> int타입의 데이터만 넣겠다는 의미
print(type(a[0]))
print(a)
b=np.array([1.1, 1.2, 1.3], dtype='f') # dtype='f' -> float타입의 데이터만 넣겠다는 의미   #i,f,s,u 다 알필요없습니다. 안 써요.
print(b)
print(type(b[0]))

print("------------")

np.seterr( divide ='ignore', invalid= 'ignore' )
a=np.array( [1,-1,0] ) 
b=np.array( [0,0,0] )
c=a/b
print(c)  # inf = 무한
print( np.log(0) )


In [ ]:
# 빈 배열 생성
empty = np.empty( (4,3))
# print(empty)    # 4X3인 빈 배열 생성  int[][] arr=new int[4][3]   -> 출력되는 값들은 메모리주소(값이 들어가기전까지는 의미없음)

# 배열 생성 
a=np.arange(10)  # 0 ~ 9 배열
b=np.zeros(10)  # 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 
c=np.ones(10)  # 1,1,1,1,1,1,1,1,1,1

a1=np.arange(3,4)   # 3~4까지 함수.     3X4를 만들고 싶다면 reshape함수 사용
b1=np.zeros( (3,4) )    # 3X4 배열 만드는 함수
c1=np.ones( (3,4) )     # 3X4 배열 만드는 함수

print(a1)
print(b1)
print(c1)


print(np.arange(5,10))   # arnage는 배열 내 인덱스 범위 지정


In [ ]:
# 배열생성 어려운거
print(np.linspace(0,100,5))    # 0부터 100까지 5등분
print(np.arange(0,101,25))
print(np.logspace(0.1,1,10))   # 0.1부터 1까지 10등분한 것의 로그값들

In [ ]:
# 배열의 변경
a=np.arange(12).reshape(3,4) # 0~11까지의 일차원배열을 3X4배열(이차원)로 재구성
print(a)
print(a.T)  # 4X3 행렬 구성 .T가 붙으면 행과 열의 위치를 바꿈
print("-----------------------")
# print(np.arange(12).reshape(6,2)) # 6X2배열로 재구성

print("-----------------------")
# b=np.arange(16).reshape(2,2,2,2)
# print(b)

a_flatten=a.flatten() #복사  # 이차원배열을 일차원으로
a_ravel=a.ravel()     #참조   # flatten()과 비슷하지만 차이점은 복사 참조 

a[0][0] =100
print(a_flatten)  
print(a_ravel)


In [ ]:
# 배열연결
# stack : stack(연결기준 설정가능), vstack(열), hstack(행), dstack(가장 마지막 차원)
a0=np.zeros((2,2))
a1=np.ones((2,3))

print(a0)
print(a1)
print("hstack", np.hstack([a0,a1])) # 2 X 5(2+3)

b0=np.zeros((2,3))
b1=np.ones((4,3))
print("vstack", np.vstack([b0,b1]))  # 6(2+4) X 3

c0 = np.zeros((3,4))
c1 = np.ones((3,4))   # 행렬 개수 같음
print("dstack", np.dstack([c0,c1])) # 행렬길이가 같을때 안쪽에 차원이 증가.  3X4X2 배열이 된다.

In [ ]:
#배열 연산    배열끼리 + * 등등 벡터연산은 for문보다 빠릅니다.

In [ ]:
%%time   
x=np.arange(0,10000)
y=np.arange(10000,20000)
z=np.empty_like(x)
for i in range(10000):
    z[i]=x[i]+y[i]
print(z)

In [ ]:
%%time   
x=np.arange(0,10000)
y=np.arange(10000,20000)
z=x+y
print(z)

In [ ]:
x=np.arange(5)
y=np.ones_like(x)   # 배열이 들어가면 같은 크기의 1로 만든 배열
print("x", x)
print("y", y)
print(x+y)

print("----------------")
a=np.vstack( [range(7)[i : i+3] for i in range(5)    ] )
print(a)

b=np.array( [[0],[1],[2],[3],[4]] )
print(b)
print(a+b)  # 행 개수만 맞으면 빈자리는 0으로 자동으로 채우고 해당 행끼리 더함

print("----------------")
c=np.arange(3)      # c = [0 1 2]
print(a+c)          # c = [[0 1 2][0 1 2][0 1 2][0 1 2][0 1 2]]
                    # a =[[0 1 2][1 2 3][2 3 4][3 4 5][4 5 6]]



In [ ]:
# 통계 min,max,std,mean,var
x= np.arange(1,6)
print(x)

print(x.min(),x.argmin(), x.max(), x.argmax(), x.sum(), x.mean())
# 최소값, 최소값이 있는 인덱스, 최댓값, 최댓값이 있는 인덱스, 합, 평균

print(np.median(x), np.std(x),np.var(x) )  
# 중앙값, 표준편차, 분산

print(np.percentile(x, 0), np.percentile(x,25), np.percentile(x,75))
# 사분위수,  25%에 해당하는 부분, 75%에 해당하는 부분

In [ ]:
x=np.array( [[1,1], [2,2], [3,3]] )
print(x.sum())    #모든 합
print(x.sum(axis=0))   # 첫번째 차원에 대해 합 [1+2+3, 1+2+3]
print(x.sum(axis=1))   # 두번째 차원에 대해 합 [1+1, 2+2, 3+3]

In [ ]:
a=np.array( [   [4,3,5,7],[1,12,11,9], [2,15,1,14] ])
b=np.sort(a)    # 기본적으로 가장 안쪽을 기준으로 정렬
print(a)
print(b)

print("--------------------")
c=np.sort(a, axis=0)  # 0번째 차원에 대해서 a의 열을 정렬
print(c)
print("--------------------")
d=np.sort(a, axis=1)  # 1번째 차원에 대해서
print(d)
print("--------------------")


In [19]:
# 랜덤이랑 확률
import numpy as np
# random 발생 함수    rand(java의 Math.random같은 것 확률이 동일하지 않아요), randn(표준편차 안에서 random), randint

x=np.random.randint(10,20, size=(10,3))  # 10 ~ 20 랜덤한 수를 10*3 배열로
print(x)
a=np.arange(10)
np.random.shuffle(a)   # 복사가 아니고 a의 내용을 바꿈
print(a)   # 순서만 랜덤으로
print(" 랜덤 초이스1 ", np.random.choice(5,5, replace=False))   # 범위, 개수, replace 중복여부(false 중복 X, true 중복 O)
print(" 랜덤 초이스2 ", np.random.choice(5,5, p=[0.1,0.1,0.1,0.1,0.6]))     # p는 각각의 확률
print(" 랜덤 초이스3 ", np.random.choice(5,10, p=[0.1,0.1,0.1,0.1,0.6]))     # p는 각각의 확률

[[13 10 17]
 [12 10 19]
 [13 15 12]
 [16 19 17]
 [18 12 13]
 [11 12 15]
 [17 16 10]
 [12 15 15]
 [16 15 18]
 [11 15 11]]
[7 6 9 2 0 4 5 8 3 1]
 랜덤 초이스1  [2 0 3 1 4]
 랜덤 초이스2  [4 4 2 4 2]
 랜덤 초이스3  [4 4 4 4 0 4 3 3 4 2]


In [48]:
# 주사위 숫자를 100번 던짐
x=np.random.randint(1,7,100)     # 인자가 3개면 범위, 범위, 사이즈
print(x)

# 동전을 10번 던짐
x=np.random.randint(0,2,10)
print(x)
print(np.count_nonzero(x))   # 앞면이 1
# for문을 써서 동전 10번 던졌을 때 앞면이 5번 이상 나올 확률을 구하기 위해
# 1000번 실행해봤습니다.
# 동전의 앞면이 5번이상 나올 확률을 구해보세요.
cnt = 0
for i in range(5,1000):
    x=np.random.randint(0,2,i)
    if np.count_nonzero(x) >= 5:
        cnt += 1
    avg = cnt/i
print(avg)


# 가격이 10000원인 주식이 있습니다. 하루동안의 수익률은 기대값이 0, 표준편차가 1인 정규분포를 따릅니다.(randn사용)
# 250일 동안의 주식 가격을 출력해보세요
x=np.random.randn(250)
print(x)
price=10000
for i in x :
    price = price * (1+i/100)
    print(price)

[2 1 1 5 1 3 1 5 5 4 4 2 4 1 6 4 6 3 5 6 2 6 3 6 6 4 3 4 6 4 6 5 1 6 4 4 5
 6 6 2 6 3 1 1 1 6 1 5 4 4 6 3 3 5 2 5 3 2 2 1 1 4 3 5 4 2 6 4 5 3 6 6 3 4
 6 3 4 2 6 1 3 4 4 3 6 6 3 5 1 4 1 3 3 6 3 2 4 1 5 3]
[0 0 0 0 1 1 1 0 0 1]
4
0.991991991991992
[-1.61792162  0.02373961  1.45973532  0.37397178 -1.68849912  0.41338916
  0.868959   -1.44533711  1.38772135  0.83639324  0.94062415 -0.81315747
  0.00753998 -1.88157354  1.01376173 -0.0637048   0.19331954 -0.43891026
  2.66246935  0.16777689  0.90092935 -0.59454456 -1.68050893  0.248659
  0.79072134 -1.70491508 -0.46774221 -1.34965363  0.85367558 -0.84851946
 -0.94425491  0.13759234 -0.73260752 -1.01997055  1.43689273 -0.913726
  0.96762841 -0.50192205  0.02867428  0.44147319 -0.00630247 -0.70330803
 -0.59842033 -0.66773963 -0.11762868 -0.1469107   0.0519833  -2.29978637
  0.32496018  0.00709832  0.80896426  0.70332337  0.49426893  0.45228347
 -1.92496683 -0.36452999  0.83185714 -0.85738224 -0.76799186  1.22297102
  0.1029577  -0.20933675 -0.

In [47]:
x=np.random.randint(5,10,10)
print(x)
print(np.unique(x))   # 중복없이 데이터 종류만 확인하고 싶을 때

# bincount 데이터가 몇개 있는지
print(np.bincount(x, minlength=11))     # min


[9 5 8 5 9 8 9 5 5 6]
[5 6 8 9]
[0 0 0 0 0 4 1 0 2 3 0]
